[build]
  base = "."

  publish = "packages/frontend/build/"

  command = "yarn build"

[build.environments]
    YARN_VERSION = "1.22.4"
    CONTEXT = "production"

[context.production.environment]
    SKIP_PREFLIGHT_CHECK = "true"
    GENERATE_SOURCEMAP = "false"
    REACT_APP_BACKEND_URL = "https://print-shop-api.herokuapp.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"
